#ifndef lexer_h_k28xi1odj37cu2jg
#define lexer_h_k28xi1odj37cu2jg

extern long int yynumbval;

enum lexsymb {
    LEX_ARRAY,
    LEX_BEGIN,
    LEX_CONST,
    LEX_DEC,
    LEX_DO,
    LEX_DOWNTO,
    LEX_ELSE,
    LEX_END,
    LEX_EXIT,
    LEX_FOR,
    LEX_FORW,
    LEX_FUNC,
    LEX_IF,
    LEX_INC,
    LEX_INT,
    LEX_OF,
    LEX_PROC,
    LEX_PROGRAM,
    LEX_READLN,
    LEX_THEN,
    LEX_TO,
    LEX_VAR,
    LEX_WHILE,
    LEX_WRITE,
    LEX_WRITELN,
    LEX_DIV,
    LEX_EXP,
    LEX_MINUS,
    LEX_MOD,
    LEX_MUL,
    LEX_PLUS,
    LEX_ASSIGN,
    LEX_EQ,
    LEX_NE,
    LEX_LT,
    LEX_GT,
    LEX_LE,
    LEX_GE,
    LEX_AND,
    LEX_NOT,
    LEX_OR,
    LEX_IDENT,
    LEX_COLON,
    LEX_COMMA,
    LEX_DOT,
    LEX_DOTDOT,
    LEX_LBRAC,
    LEX_RBRAC,
    LEX_LRBRAC,
    LEX_RRBRAC,
    LEX_NUMB,
    LEX_SEMICOLON,
    LEX_EOI
};

#endif /* lexer_h_k28xi1odj37cu2jg */
